# fly.toml app configuration file generated for update-yjprjt-backend on 2025-08-11T06:27:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml app configuration file
app = "update-yjprjt-backend"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
